title: v86online
email: support@ttnrtsite.me
description: >- # this means to ignore newlines until "baseurl:"
  View the health reports from all servers in our network
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  TTNRT

plugins:
  - jekyll-feed
  - jekyll-seo-tag
